---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible_test"
      instance_type: t2.micro
      security_group: default
      region: us-west-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        environment: "{{ item.name }}"
    loop:
      - { image: "ami-0e6a50b0059fd2cc3", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-0e6a50b0059fd2cc3", name: "manage-node-2" } # to your account
      - { image: "ami-0623300d1b7caee89", name: "manage-node-3" }
