---
- hosts: all
  become: true

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Enable universe repository
      ansible.builtin.apt_repository:
        repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present

    - name: Install security updates
      ansible.builtin.apt:
        name:
          - openssl
          - openssh-server
        state: latest
      ignore_errors: yes

    - name: Check if docker is installed
      ansible.builtin.command: docker --version
      register: docker_check
      ignore_errors: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present
      when: docker_check.failed
